### ISSUE TITLE
Hashing problem in version 10.3.11.27

### ISSUE THREAD

**Issue by diegoin4apps** [Smarteon/loxone-java#56]
I have a problem parsing the next command:
**/jdev/sys/getkey2/{{user}}**

The error message shown is as follows:
**Can't parse response: Unrecognized field "hashAlg" (class cz.smarteon.loxone.message.Hashing), not marked as ignorable (2 known properties: "salt", "key"])**

The problem is that this new version contains the following additional parameter: "hashAlg" and the class constructor only knows the "salt" and "key" properties.

Would it be possible to update the class so that it ignores unexpected properties?

Thanks in advance.

**Comment by jimirocks** [comment]
Hello, thanks for report. Unfortunately I haven't upgraded to 10.3 yet and beeing busy with other things I can't promise the upgrade soon (hopefully in few weeks). In the meantime:
1. Would be nice if you provide the **complete payload example** (with key part mangled)
2. I will be happy to **review and accept pull request**
3. Please note that since version 0.4.0 there are some **major backward incompatible changes** in master already (so the adoption of the future 0.5.0 would have some effort for your - try to build and use current master locally for reference)
